### ISSUE TITLE
`make install` fail on macOS 12.3 due to `-D` flag

### ISSUE THREAD

**Issue by angrychimp** [jirutka/tty-copy#4]
On macOS 12.3 the available `install` command does not have a `-D` flag. I'm assuming you're trying to create the target folder if it doesn't exist, which on Darwin seems to be `-d` (lowercase).

**Comment by jirutka** [comment]
I know about this caveat, I just hadn’t originally planned on macOS support, so I didn’t write this Makefile with BSD compatibility in mind. Thanks for noticing it!
